void ttbar()
{
//=========Macro generated from canvas: histogram/histogram
//=========  (Wed Jun 15 08:21:16 2022) by ROOT version 6.18/04
   TCanvas *histogram = new TCanvas("histogram", "histogram",0,0,800,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   histogram->SetHighLightColor(2);
   histogram->Range(0,0,1,1);
   histogram->SetFillColor(0);
   histogram->SetBorderMode(0);
   histogram->SetBorderSize(2);
   histogram->SetLeftMargin(0);
   histogram->SetRightMargin(0);
   histogram->SetTopMargin(0);
   histogram->SetBottomMargin(0);
   histogram->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: main
   TPad *main = new TPad("main", "main",0,0,1,1);
   main->Draw();
   main->cd();
   main->Range(-0.2025316,-5.902306,1.063291,5.023407);
   main->SetFillColor(0);
   main->SetFillStyle(4000);
   main->SetBorderMode(0);
   main->SetBorderSize(0);
   main->SetLogy();
   main->SetTickx(1);
   main->SetTicky(1);
   main->SetLeftMargin(0.16);
   main->SetRightMargin(0.05);
   main->SetTopMargin(0.05);
   main->SetBottomMargin(0.55);
   main->SetFrameBorderMode(0);
   main->SetFrameBorderMode(0);
   
   TH1F *Graph_master = new TH1F("Graph_master","Main Coordinate System",7,0,1);
   Graph_master->SetMinimum(1.278899);
   Graph_master->SetMaximum(30000);
   Graph_master->SetStats(0);
   Graph_master->SetLineColor(4);
   Graph_master->SetLineStyle(7);
   Graph_master->SetLineWidth(2);
   Graph_master->SetMarkerColor(4);
   Graph_master->SetMarkerStyle(21);
   Graph_master->GetXaxis()->SetTitle("Remapped DNN output G");
   Graph_master->GetXaxis()->SetLabelFont(42);
   Graph_master->GetXaxis()->SetLabelOffset(0);
   Graph_master->GetXaxis()->SetLabelSize(0);
   Graph_master->GetXaxis()->SetTitleSize(0);
   Graph_master->GetXaxis()->SetTitleFont(42);
   Graph_master->GetYaxis()->SetTitle("Events / 0.14");
   Graph_master->GetYaxis()->SetLabelFont(42);
   Graph_master->GetYaxis()->SetLabelOffset(0.00625);
   Graph_master->GetYaxis()->SetTitleOffset(1.75);
   Graph_master->GetYaxis()->SetTitleFont(42);
   Graph_master->GetZaxis()->SetLabelFont(42);
   Graph_master->GetZaxis()->SetLabelSize(0.035);
   Graph_master->GetZaxis()->SetTitleSize(0.035);
   Graph_master->GetZaxis()->SetTitleOffset(1);
   Graph_master->GetZaxis()->SetTitleFont(42);
   Graph_master->Draw("hist");
   
   THStack *stack = new THStack();
   stack->SetName("stack");
   stack->SetTitle("Background Stack");
   
   TH1F *stack_stack_1 = new TH1F("stack_stack_1","Background Stack",7,0,1);
   stack_stack_1->SetMinimum(0.7157926);
   stack_stack_1->SetMaximum(11172.76);
   stack_stack_1->SetDirectory(0);
   stack_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   stack_stack_1->SetLineColor(ci);
   stack_stack_1->GetXaxis()->SetLabelFont(42);
   stack_stack_1->GetXaxis()->SetLabelSize(0.035);
   stack_stack_1->GetXaxis()->SetTitleSize(0.035);
   stack_stack_1->GetXaxis()->SetTitleOffset(1);
   stack_stack_1->GetXaxis()->SetTitleFont(42);
   stack_stack_1->GetYaxis()->SetLabelFont(42);
   stack_stack_1->GetYaxis()->SetLabelSize(0.035);
   stack_stack_1->GetYaxis()->SetTitleSize(0.035);
   stack_stack_1->GetYaxis()->SetTitleFont(42);
   stack_stack_1->GetZaxis()->SetLabelFont(42);
   stack_stack_1->GetZaxis()->SetLabelSize(0.035);
   stack_stack_1->GetZaxis()->SetTitleSize(0.035);
   stack_stack_1->GetZaxis()->SetTitleOffset(1);
   stack_stack_1->GetZaxis()->SetTitleFont(42);
   stack->SetHistogram(stack_stack_1);
   
   
   TH1F *hist_Nominal_stack_1 = new TH1F("hist_Nominal_stack_1","Nominal",7,0,1);
   hist_Nominal_stack_1->SetBinContent(1,6539.759);
   hist_Nominal_stack_1->SetBinContent(2,200.869);
   hist_Nominal_stack_1->SetBinContent(3,48.72853);
   hist_Nominal_stack_1->SetBinContent(4,15.80952);
   hist_Nominal_stack_1->SetBinContent(5,8.886186);
   hist_Nominal_stack_1->SetBinContent(6,4.033584);
   hist_Nominal_stack_1->SetBinContent(7,2.524963);
   hist_Nominal_stack_1->SetBinError(1,16.34584);
   hist_Nominal_stack_1->SetBinError(2,2.88276);
   hist_Nominal_stack_1->SetBinError(3,1.413911);
   hist_Nominal_stack_1->SetBinError(4,0.8121189);
   hist_Nominal_stack_1->SetBinError(5,0.6057846);
   hist_Nominal_stack_1->SetBinError(6,0.4071981);
   hist_Nominal_stack_1->SetBinError(7,0.3295161);
   hist_Nominal_stack_1->SetEntries(182508);
   hist_Nominal_stack_1->SetStats(0);
   hist_Nominal_stack_1->SetFillColor(1);
   hist_Nominal_stack_1->SetFillStyle(0);
   hist_Nominal_stack_1->SetLineWidth(2);
   hist_Nominal_stack_1->GetXaxis()->SetTitle("Remapped DNN output G");
   hist_Nominal_stack_1->GetXaxis()->SetLabelFont(42);
   hist_Nominal_stack_1->GetXaxis()->SetLabelSize(0.035);
   hist_Nominal_stack_1->GetXaxis()->SetTitleSize(0.035);
   hist_Nominal_stack_1->GetXaxis()->SetTitleOffset(1);
   hist_Nominal_stack_1->GetXaxis()->SetTitleFont(42);
   hist_Nominal_stack_1->GetYaxis()->SetLabelFont(42);
   hist_Nominal_stack_1->GetYaxis()->SetLabelSize(0.035);
   hist_Nominal_stack_1->GetYaxis()->SetTitleSize(0.035);
   hist_Nominal_stack_1->GetYaxis()->SetTitleFont(42);
   hist_Nominal_stack_1->GetZaxis()->SetLabelFont(42);
   hist_Nominal_stack_1->GetZaxis()->SetLabelSize(0.035);
   hist_Nominal_stack_1->GetZaxis()->SetTitleSize(0.035);
   hist_Nominal_stack_1->GetZaxis()->SetTitleOffset(1);
   hist_Nominal_stack_1->GetZaxis()->SetTitleFont(42);
   stack->Add(hist_Nominal_stack_1,"");
   stack->Draw("hist same");
   
   TH1F *hist_Up__1 = new TH1F("hist_Up__1","Processed Up",7,0,1);
   hist_Up__1->SetBinContent(1,6529.09);
   hist_Up__1->SetBinContent(2,202.4337);
   hist_Up__1->SetBinContent(3,52.08695);
   hist_Up__1->SetBinContent(4,18.38556);
   hist_Up__1->SetBinContent(5,10.70998);
   hist_Up__1->SetBinContent(6,4.861432);
   hist_Up__1->SetBinContent(7,3.043184);
   hist_Up__1->SetBinError(1,43.26348);
   hist_Up__1->SetBinError(2,7.499823);
   hist_Up__1->SetBinError(3,3.838105);
   hist_Up__1->SetBinError(4,2.307415);
   hist_Up__1->SetBinError(5,1.387404);
   hist_Up__1->SetBinError(6,1.066983);
   hist_Up__1->SetBinError(7,0.7278441);
   hist_Up__1->SetEntries(182512);
   hist_Up__1->SetStats(0);
   hist_Up__1->SetLineColor(4);
   hist_Up__1->SetLineStyle(7);
   hist_Up__1->SetLineWidth(2);
   hist_Up__1->SetMarkerColor(4);
   hist_Up__1->SetMarkerStyle(21);
   hist_Up__1->GetXaxis()->SetTitle("Remapped DNN output G");
   hist_Up__1->GetXaxis()->SetLabelFont(42);
   hist_Up__1->GetXaxis()->SetLabelSize(0.035);
   hist_Up__1->GetXaxis()->SetTitleSize(0.035);
   hist_Up__1->GetXaxis()->SetTitleOffset(1);
   hist_Up__1->GetXaxis()->SetTitleFont(42);
   hist_Up__1->GetYaxis()->SetLabelFont(42);
   hist_Up__1->GetYaxis()->SetLabelSize(0.035);
   hist_Up__1->GetYaxis()->SetTitleSize(0.035);
   hist_Up__1->GetYaxis()->SetTitleFont(42);
   hist_Up__1->GetZaxis()->SetLabelFont(42);
   hist_Up__1->GetZaxis()->SetLabelSize(0.035);
   hist_Up__1->GetZaxis()->SetTitleSize(0.035);
   hist_Up__1->GetZaxis()->SetTitleOffset(1);
   hist_Up__1->GetZaxis()->SetTitleFont(42);
   hist_Up__1->Draw("ep same");
   
   TH1F *hist_Down__2 = new TH1F("hist_Down__2","Processed Down",7,0,1);
   hist_Down__2->SetBinContent(1,6550.428);
   hist_Down__2->SetBinContent(2,199.3042);
   hist_Down__2->SetBinContent(3,45.37011);
   hist_Down__2->SetBinContent(4,13.23348);
   hist_Down__2->SetBinContent(5,7.062396);
   hist_Down__2->SetBinContent(6,3.205736);
   hist_Down__2->SetBinContent(7,2.006743);
   hist_Down__2->SetBinError(1,43.26348);
   hist_Down__2->SetBinError(2,7.499823);
   hist_Down__2->SetBinError(3,3.838105);
   hist_Down__2->SetBinError(4,2.307415);
   hist_Down__2->SetBinError(5,1.387404);
   hist_Down__2->SetBinError(6,1.066983);
   hist_Down__2->SetBinError(7,0.7278441);
   hist_Down__2->SetEntries(210);
   hist_Down__2->SetStats(0);
   hist_Down__2->SetLineColor(64);
   hist_Down__2->SetLineStyle(7);
   hist_Down__2->SetLineWidth(2);
   hist_Down__2->SetMarkerColor(64);
   hist_Down__2->SetMarkerStyle(21);
   hist_Down__2->GetXaxis()->SetTitle("Remapped DNN output G");
   hist_Down__2->GetXaxis()->SetLabelFont(42);
   hist_Down__2->GetXaxis()->SetLabelSize(0.035);
   hist_Down__2->GetXaxis()->SetTitleSize(0.035);
   hist_Down__2->GetXaxis()->SetTitleOffset(1);
   hist_Down__2->GetXaxis()->SetTitleFont(42);
   hist_Down__2->GetYaxis()->SetLabelFont(42);
   hist_Down__2->GetYaxis()->SetLabelSize(0.035);
   hist_Down__2->GetYaxis()->SetTitleSize(0.035);
   hist_Down__2->GetYaxis()->SetTitleFont(42);
   hist_Down__2->GetZaxis()->SetLabelFont(42);
   hist_Down__2->GetZaxis()->SetLabelSize(0.035);
   hist_Down__2->GetZaxis()->SetTitleSize(0.035);
   hist_Down__2->GetZaxis()->SetTitleOffset(1);
   hist_Down__2->GetZaxis()->SetTitleFont(42);
   hist_Down__2->Draw("ep same");
   
   TH1F *hist_HWWVBFSimpleUp__3 = new TH1F("hist_HWWVBFSimpleUp__3","Raw Up",7,0,1);
   hist_HWWVBFSimpleUp__3->SetBinContent(1,6524.553);
   hist_HWWVBFSimpleUp__3->SetBinContent(2,208.2027);
   hist_HWWVBFSimpleUp__3->SetBinContent(3,50.2123);
   hist_HWWVBFSimpleUp__3->SetBinContent(4,20.45092);
   hist_HWWVBFSimpleUp__3->SetBinContent(5,9.607558);
   hist_HWWVBFSimpleUp__3->SetBinContent(6,5.229181);
   hist_HWWVBFSimpleUp__3->SetBinContent(7,2.354816);
   hist_HWWVBFSimpleUp__3->SetBinError(1,43.26348);
   hist_HWWVBFSimpleUp__3->SetBinError(2,7.499823);
   hist_HWWVBFSimpleUp__3->SetBinError(3,3.838105);
   hist_HWWVBFSimpleUp__3->SetBinError(4,2.307415);
   hist_HWWVBFSimpleUp__3->SetBinError(5,1.387404);
   hist_HWWVBFSimpleUp__3->SetBinError(6,1.066983);
   hist_HWWVBFSimpleUp__3->SetBinError(7,0.7278441);
   hist_HWWVBFSimpleUp__3->SetEntries(284);
   hist_HWWVBFSimpleUp__3->SetStats(0);
   hist_HWWVBFSimpleUp__3->SetFillColor(2);
   hist_HWWVBFSimpleUp__3->SetLineColor(2);
   hist_HWWVBFSimpleUp__3->SetLineWidth(2);
   hist_HWWVBFSimpleUp__3->SetMarkerColor(2);
   hist_HWWVBFSimpleUp__3->SetMarkerStyle(20);
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetTitle("Remapped DNN output G");
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetTitleOffset(1);
   hist_HWWVBFSimpleUp__3->GetXaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleUp__3->GetYaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleUp__3->GetYaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleUp__3->GetYaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleUp__3->GetYaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleUp__3->GetZaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleUp__3->GetZaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleUp__3->GetZaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleUp__3->GetZaxis()->SetTitleOffset(1);
   hist_HWWVBFSimpleUp__3->GetZaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleUp__3->Draw("ep same");
   
   TH1F *hist_HWWVBFSimpleDown__4 = new TH1F("hist_HWWVBFSimpleDown__4","Raw Down",7,0,1);
   hist_HWWVBFSimpleDown__4->SetBinContent(1,6554.965);
   hist_HWWVBFSimpleDown__4->SetBinContent(2,193.535);
   hist_HWWVBFSimpleDown__4->SetBinContent(3,47.24475);
   hist_HWWVBFSimpleDown__4->SetBinContent(4,11.16801);
   hist_HWWVBFSimpleDown__4->SetBinContent(5,8.164803);
   hist_HWWVBFSimpleDown__4->SetBinContent(6,2.837953);
   hist_HWWVBFSimpleDown__4->SetBinContent(7,2.695118);
   hist_HWWVBFSimpleDown__4->SetBinError(1,43.28792);
   hist_HWWVBFSimpleDown__4->SetBinError(2,7.432772);
   hist_HWWVBFSimpleDown__4->SetBinError(3,3.811592);
   hist_HWWVBFSimpleDown__4->SetBinError(4,2.170391);
   hist_HWWVBFSimpleDown__4->SetBinError(5,1.354502);
   hist_HWWVBFSimpleDown__4->SetBinError(6,1.000253);
   hist_HWWVBFSimpleDown__4->SetBinError(7,0.7430684);
   hist_HWWVBFSimpleDown__4->SetEntries(202);
   hist_HWWVBFSimpleDown__4->SetStats(0);
   hist_HWWVBFSimpleDown__4->SetFillColor(95);
   hist_HWWVBFSimpleDown__4->SetLineColor(95);
   hist_HWWVBFSimpleDown__4->SetLineWidth(2);
   hist_HWWVBFSimpleDown__4->SetMarkerColor(95);
   hist_HWWVBFSimpleDown__4->SetMarkerStyle(20);
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetTitle("Remapped DNN output G");
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetTitleOffset(1);
   hist_HWWVBFSimpleDown__4->GetXaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleDown__4->GetYaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleDown__4->GetYaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleDown__4->GetYaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleDown__4->GetYaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleDown__4->GetZaxis()->SetLabelFont(42);
   hist_HWWVBFSimpleDown__4->GetZaxis()->SetLabelSize(0.035);
   hist_HWWVBFSimpleDown__4->GetZaxis()->SetTitleSize(0.035);
   hist_HWWVBFSimpleDown__4->GetZaxis()->SetTitleOffset(1);
   hist_HWWVBFSimpleDown__4->GetZaxis()->SetTitleFont(42);
   hist_HWWVBFSimpleDown__4->Draw("ep same");
   
   TLegend *leg = new TLegend(0.59,0.7325,0.9,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.034);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("hist_Up"," Processed Up","lep");
   entry->SetLineColor(4);
   entry->SetLineStyle(7);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_Down"," Processed Down","lep");
   entry->SetLineColor(64);
   entry->SetLineStyle(7);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(64);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_HWWVBFSimpleUp"," Raw Up","lep");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_HWWVBFSimpleDown"," Raw Down","lep");
   entry->SetLineColor(95);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(95);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hist_Nominal_stack_1"," Nominal","f");
   entry->SetFillColor(1);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.95,0.96,"theo_ttbar_matching_MECOff_grecOff/SR/ttbar");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.024);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *Graph_master_copy = new TH1F("Graph_master_copy","Main Coordinate System",7,0,1);
   Graph_master_copy->SetMinimum(1.278899);
   Graph_master_copy->SetMaximum(30000);
   Graph_master_copy->SetDirectory(0);
   Graph_master_copy->SetStats(0);
   Graph_master_copy->SetLineColor(4);
   Graph_master_copy->SetLineStyle(7);
   Graph_master_copy->SetLineWidth(2);
   Graph_master_copy->SetMarkerColor(4);
   Graph_master_copy->SetMarkerStyle(21);
   Graph_master_copy->GetXaxis()->SetTitle("Remapped DNN output G");
   Graph_master_copy->GetXaxis()->SetLabelFont(42);
   Graph_master_copy->GetXaxis()->SetLabelOffset(0);
   Graph_master_copy->GetXaxis()->SetLabelSize(0);
   Graph_master_copy->GetXaxis()->SetTitleSize(0);
   Graph_master_copy->GetXaxis()->SetTitleFont(42);
   Graph_master_copy->GetYaxis()->SetTitle("Events / 0.14");
   Graph_master_copy->GetYaxis()->SetLabelFont(42);
   Graph_master_copy->GetYaxis()->SetLabelOffset(0.00625);
   Graph_master_copy->GetYaxis()->SetTitleOffset(1.75);
   Graph_master_copy->GetYaxis()->SetTitleFont(42);
   Graph_master_copy->GetZaxis()->SetLabelFont(42);
   Graph_master_copy->GetZaxis()->SetLabelSize(0.035);
   Graph_master_copy->GetZaxis()->SetTitleSize(0.035);
   Graph_master_copy->GetZaxis()->SetTitleOffset(1);
   Graph_master_copy->GetZaxis()->SetTitleFont(42);
   Graph_master_copy->Draw("sameaxis");
   main->Modified();
   histogram->cd();
  
// ------------>Primitives in pad: sub
   TPad *sub = new TPad("sub", "sub",0,0,1,0.55);
   sub->Draw();
   sub->cd();
   sub->Range(0,0,1,1);
   sub->SetFillColor(0);
   sub->SetFillStyle(4000);
   sub->SetBorderMode(0);
   sub->SetBorderSize(0);
   sub->SetGridy();
   sub->SetTickx(1);
   sub->SetTicky(1);
   sub->SetLeftMargin(0.16);
   sub->SetRightMargin(0.05);
   sub->SetTopMargin(0);
   sub->SetBottomMargin(0.2909091);
   sub->SetFrameBorderMode(0);
   
   TH1F *ratioDenominatorErrors_totalStack__5 = new TH1F("ratioDenominatorErrors_totalStack__5","SM",7,0,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(1,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(2,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(3,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(4,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(5,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(6,1);
   ratioDenominatorErrors_totalStack__5->SetBinContent(7,1);
   ratioDenominatorErrors_totalStack__5->SetBinError(1,0.002499456);
   ratioDenominatorErrors_totalStack__5->SetBinError(2,0.01435144);
   ratioDenominatorErrors_totalStack__5->SetBinError(3,0.02901609);
   ratioDenominatorErrors_totalStack__5->SetBinError(4,0.05136897);
   ratioDenominatorErrors_totalStack__5->SetBinError(5,0.0681715);
   ratioDenominatorErrors_totalStack__5->SetBinError(6,0.1009519);
   ratioDenominatorErrors_totalStack__5->SetBinError(7,0.1305033);
   ratioDenominatorErrors_totalStack__5->SetMinimum(0.45);
   ratioDenominatorErrors_totalStack__5->SetMaximum(1.55);
   ratioDenominatorErrors_totalStack__5->SetEntries(182508);
   ratioDenominatorErrors_totalStack__5->SetStats(0);
   ratioDenominatorErrors_totalStack__5->SetFillColor(14);
   ratioDenominatorErrors_totalStack__5->SetFillStyle(3245);

   ci = TColor::GetColor("#0000ff");
   ratioDenominatorErrors_totalStack__5->SetLineColor(ci);
   ratioDenominatorErrors_totalStack__5->SetLineStyle(7);
   ratioDenominatorErrors_totalStack__5->SetLineWidth(2);
   ratioDenominatorErrors_totalStack__5->SetMarkerColor(4);
   ratioDenominatorErrors_totalStack__5->SetMarkerStyle(0);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetTitle("Remapped DNN output G");
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetLabelFont(42);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetLabelOffset(0.00625);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetLabelSize(0.07272727);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetTitleSize(0.07272727);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetTickLength(0.05454545);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetTitleOffset(1.75);
   ratioDenominatorErrors_totalStack__5->GetXaxis()->SetTitleFont(42);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetTitle("Variation / Nominal");
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetLabelFont(42);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetLabelOffset(0.0034375);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetLabelSize(0.07272727);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetTitleSize(0.07272727);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetTitleOffset(0.9625);
   ratioDenominatorErrors_totalStack__5->GetYaxis()->SetTitleFont(42);
   ratioDenominatorErrors_totalStack__5->GetZaxis()->SetLabelFont(42);
   ratioDenominatorErrors_totalStack__5->GetZaxis()->SetLabelSize(0.035);
   ratioDenominatorErrors_totalStack__5->GetZaxis()->SetTitleSize(0.035);
   ratioDenominatorErrors_totalStack__5->GetZaxis()->SetTitleOffset(1);
   ratioDenominatorErrors_totalStack__5->GetZaxis()->SetTitleFont(42);
   ratioDenominatorErrors_totalStack__5->Draw("E2");
   TLine *line = new TLine(0,1,1,1);
   line->SetLineStyle(7);
   line->SetLineWidth(2);
   line->Draw();
   
   TH1F *ratio_hist_Up_totalStack__6 = new TH1F("ratio_hist_Up_totalStack__6","Processed Up",7,0,1);
   ratio_hist_Up_totalStack__6->SetBinContent(1,0.9983686);
   ratio_hist_Up_totalStack__6->SetBinContent(2,1.00779);
   ratio_hist_Up_totalStack__6->SetBinContent(3,1.068921);
   ratio_hist_Up_totalStack__6->SetBinContent(4,1.162942);
   ratio_hist_Up_totalStack__6->SetBinContent(5,1.205239);
   ratio_hist_Up_totalStack__6->SetBinContent(6,1.205239);
   ratio_hist_Up_totalStack__6->SetBinContent(7,1.205239);
   ratio_hist_Up_totalStack__6->SetBinError(1,0.006615455);
   ratio_hist_Up_totalStack__6->SetBinError(2,0.03733689);
   ratio_hist_Up_totalStack__6->SetBinError(3,0.07876505);
   ratio_hist_Up_totalStack__6->SetBinError(4,0.145951);
   ratio_hist_Up_totalStack__6->SetBinError(5,0.1561305);
   ratio_hist_Up_totalStack__6->SetBinError(6,0.2645247);
   ratio_hist_Up_totalStack__6->SetBinError(7,0.2882593);
   ratio_hist_Up_totalStack__6->SetEntries(182512);
   ratio_hist_Up_totalStack__6->SetStats(0);
   ratio_hist_Up_totalStack__6->SetLineColor(4);
   ratio_hist_Up_totalStack__6->SetLineStyle(7);
   ratio_hist_Up_totalStack__6->SetLineWidth(2);
   ratio_hist_Up_totalStack__6->SetMarkerColor(4);
   ratio_hist_Up_totalStack__6->SetMarkerStyle(21);
   ratio_hist_Up_totalStack__6->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_Up_totalStack__6->GetXaxis()->SetLabelFont(42);
   ratio_hist_Up_totalStack__6->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_Up_totalStack__6->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_Up_totalStack__6->GetXaxis()->SetTitleOffset(1);
   ratio_hist_Up_totalStack__6->GetXaxis()->SetTitleFont(42);
   ratio_hist_Up_totalStack__6->GetYaxis()->SetLabelFont(42);
   ratio_hist_Up_totalStack__6->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_Up_totalStack__6->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_Up_totalStack__6->GetYaxis()->SetTitleFont(42);
   ratio_hist_Up_totalStack__6->GetZaxis()->SetLabelFont(42);
   ratio_hist_Up_totalStack__6->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_Up_totalStack__6->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_Up_totalStack__6->GetZaxis()->SetTitleOffset(1);
   ratio_hist_Up_totalStack__6->GetZaxis()->SetTitleFont(42);
   ratio_hist_Up_totalStack__6->Draw("histSAME");
   
   TH1F *ratio_hist_Down_totalStack__7 = new TH1F("ratio_hist_Down_totalStack__7","Processed Down",7,0,1);
   ratio_hist_Down_totalStack__7->SetBinContent(1,1.001631);
   ratio_hist_Down_totalStack__7->SetBinContent(2,0.9922101);
   ratio_hist_Down_totalStack__7->SetBinContent(3,0.931079);
   ratio_hist_Down_totalStack__7->SetBinContent(4,0.8370575);
   ratio_hist_Down_totalStack__7->SetBinContent(5,0.7947612);
   ratio_hist_Down_totalStack__7->SetBinContent(6,0.7947612);
   ratio_hist_Down_totalStack__7->SetBinContent(7,0.7947611);
   ratio_hist_Down_totalStack__7->SetBinError(1,0.006615455);
   ratio_hist_Down_totalStack__7->SetBinError(2,0.03733689);
   ratio_hist_Down_totalStack__7->SetBinError(3,0.07876505);
   ratio_hist_Down_totalStack__7->SetBinError(4,0.145951);
   ratio_hist_Down_totalStack__7->SetBinError(5,0.1561305);
   ratio_hist_Down_totalStack__7->SetBinError(6,0.2645247);
   ratio_hist_Down_totalStack__7->SetBinError(7,0.2882593);
   ratio_hist_Down_totalStack__7->SetEntries(210);
   ratio_hist_Down_totalStack__7->SetStats(0);
   ratio_hist_Down_totalStack__7->SetLineColor(64);
   ratio_hist_Down_totalStack__7->SetLineStyle(7);
   ratio_hist_Down_totalStack__7->SetLineWidth(2);
   ratio_hist_Down_totalStack__7->SetMarkerColor(64);
   ratio_hist_Down_totalStack__7->SetMarkerStyle(21);
   ratio_hist_Down_totalStack__7->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_Down_totalStack__7->GetXaxis()->SetLabelFont(42);
   ratio_hist_Down_totalStack__7->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_Down_totalStack__7->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_Down_totalStack__7->GetXaxis()->SetTitleOffset(1);
   ratio_hist_Down_totalStack__7->GetXaxis()->SetTitleFont(42);
   ratio_hist_Down_totalStack__7->GetYaxis()->SetLabelFont(42);
   ratio_hist_Down_totalStack__7->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_Down_totalStack__7->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_Down_totalStack__7->GetYaxis()->SetTitleFont(42);
   ratio_hist_Down_totalStack__7->GetZaxis()->SetLabelFont(42);
   ratio_hist_Down_totalStack__7->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_Down_totalStack__7->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_Down_totalStack__7->GetZaxis()->SetTitleOffset(1);
   ratio_hist_Down_totalStack__7->GetZaxis()->SetTitleFont(42);
   ratio_hist_Down_totalStack__7->Draw("histSAME");
   
   TH1F *ratio_hist_HWWVBFSimpleUp_totalStack__8 = new TH1F("ratio_hist_HWWVBFSimpleUp_totalStack__8","Raw Up",7,0,1);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(1,0.9976749);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(2,1.03651);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(3,1.03045);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(4,1.293583);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(5,1.081179);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(6,1.296411);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinContent(7,0.9326141);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(1,0.006615455);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(2,0.03733689);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(3,0.07876505);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(4,0.145951);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(5,0.1561305);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(6,0.2645247);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetBinError(7,0.2882593);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetEntries(284);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetStats(0);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetFillColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetLineColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetLineWidth(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetMarkerColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->SetMarkerStyle(20);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetXaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetYaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetYaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetZaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetZaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->GetZaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__8->Draw("P ESAME");
   
   TH1F *ratio_hist_HWWVBFSimpleUp_totalStack__9 = new TH1F("ratio_hist_HWWVBFSimpleUp_totalStack__9","Raw Up",7,0,1);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(1,0.9976749);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(2,1.03651);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(3,1.03045);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(4,1.293583);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(5,1.081179);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(6,1.296411);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinContent(7,0.9326141);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(1,0.006615455);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(2,0.03733689);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(3,0.07876505);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(4,0.145951);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(5,0.1561305);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(6,0.2645247);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetBinError(7,0.2882593);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetEntries(284);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetStats(0);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetFillColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetLineColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetLineWidth(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetMarkerColor(2);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetMarkerStyle(20);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->SetMarkerSize(0);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetXaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetYaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetYaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetZaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetZaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->GetZaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleUp_totalStack__9->Draw("SAME P E0");
   
   TH1F *ratio_hist_HWWVBFSimpleDown_totalStack__10 = new TH1F("ratio_hist_HWWVBFSimpleDown_totalStack__10","Raw Down",7,0,1);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(1,1.002325);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(2,0.9634889);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(3,0.9695501);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(4,0.7064106);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(5,0.9188197);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(6,0.7035809);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinContent(7,1.067389);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(1,0.006619192);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(2,0.03700309);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(3,0.07822095);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(4,0.1372838);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(5,0.1524278);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(6,0.2479811);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetBinError(7,0.2942888);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetEntries(202);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetStats(0);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetFillColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetLineColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetLineWidth(2);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetMarkerColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->SetMarkerStyle(20);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetXaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetYaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetYaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetZaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetZaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->GetZaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__10->Draw("P ESAME");
   
   TH1F *ratio_hist_HWWVBFSimpleDown_totalStack__11 = new TH1F("ratio_hist_HWWVBFSimpleDown_totalStack__11","Raw Down",7,0,1);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(1,1.002325);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(2,0.9634889);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(3,0.9695501);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(4,0.7064106);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(5,0.9188197);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(6,0.7035809);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinContent(7,1.067389);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(1,0.006619192);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(2,0.03700309);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(3,0.07822095);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(4,0.1372838);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(5,0.1524278);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(6,0.2479811);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetBinError(7,0.2942888);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetEntries(202);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetStats(0);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetFillColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetLineColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetLineWidth(2);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetMarkerColor(95);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetMarkerStyle(20);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->SetMarkerSize(0);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetTitle("Remapped DNN output G");
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetXaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetYaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetYaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetYaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetYaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetZaxis()->SetLabelFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetZaxis()->SetLabelSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetZaxis()->SetTitleSize(0.035);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetZaxis()->SetTitleOffset(1);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->GetZaxis()->SetTitleFont(42);
   ratio_hist_HWWVBFSimpleDown_totalStack__11->Draw("SAME P E0");
   sub->Modified();
   histogram->cd();
   histogram->Modified();
   histogram->cd();
   histogram->SetSelected(histogram);
}
